In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv('train.csv')
df.head()
X_train= df

In [2]:
4250*80/100 #meglio usare

3400.0

In [3]:
train_num = X_train.drop(['state','area_code','international_plan','voice_mail_plan','churn'],axis='columns')

In [4]:
from sklearn import preprocessing

scaling numbers

In [5]:
scaled_num = preprocessing.MinMaxScaler().fit_transform(train_num)
cols = train_num.columns.values
scaled_num = pd.DataFrame(data = scaled_num, columns = cols)
scaled_num

,account_length,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls
0,0.438017,0.500000,0.459744,0.745455,0.459672,0.544114,0.605882,0.544204,0.644051,0.588571,0.644344,0.685,0.15,0.685185,0.111111
1,0.561983,0.000000,0.692461,0.690909,0.692436,0.337323,0.647059,0.337263,0.411646,0.594286,0.411930,0.610,0.25,0.609259,0.000000
2,0.342975,0.000000,0.851778,0.430303,0.851740,0.172279,0.517647,0.172233,0.498481,0.508571,0.498593,0.330,0.35,0.329630,0.222222
3,0.305785,0.000000,0.474253,0.684848,0.474230,0.412747,0.717647,0.412901,0.473165,0.691429,0.473270,0.505,0.15,0.505556,0.333333
4,0.495868,0.461538,0.620768,0.533333,0.620649,0.969942,0.635294,0.969876,0.538228,0.674286,0.538548,0.375,0.35,0.375926,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,0.338843,0.000000,0.535704,0.424242,0.535643,0.678542,0.517647,0.678454,0.541013,0.451429,0.541362,0.515,0.30,0.514815,0.000000
4246,0.297521,0.000000,0.506117,0.539394,0.506024,0.365154,0.482353,0.365095,0.471392,0.508571,0.471581,0.575,0.30,0.575926,0.333333
4247,0.305785,0.000000,0.485633,0.612121,0.485609,0.537434,0.741176,0.537328,0.326835,0.594286,0.326956,0.345,0.35,0.344444,0.111111
4248,0.202479,0.769231,0.670555,0.769697,0.670515,0.620651,0.741176,0.620825,0.753165,0.662857,0.753517,0.495,0.25,0.494444,0.222222
4249,0.351240,0.653846,0.368137,0.618182,0.368139,0.743390,0.611765,0.743287,0.391899,0.571429,0.392234,0.465,0.80,0.464815,0.000000

encoding categoricals

In [6]:
train_str = X_train.drop(['account_length','number_vmail_messages','total_day_minutes','total_day_calls','total_day_charge','total_eve_minutes','total_eve_calls','total_eve_charge','total_night_minutes','total_night_calls','total_night_charge','total_intl_minutes','total_intl_calls','total_intl_charge','number_customer_service_calls'], axis = 'columns')
train_str

     state      area_code international_plan voice_mail_plan churn
0       OH  area_code_415                 no             yes    no
1       NJ  area_code_415                 no              no    no
2       OH  area_code_408                yes              no    no
3       OK  area_code_415                yes              no    no
4       MA  area_code_510                 no             yes    no
...    ...            ...                ...             ...   ...
4245    MT  area_code_415                 no              no    no
4246    WV  area_code_408                 no              no    no
4247    NC  area_code_408                 no              no    no
4248    HI  area_code_408                 no             yes    no
4249    VT  area_code_415                 no             yes    no

[4250 rows x 5 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
str_ft=train_str
str_ft.state = le.fit_transform(str_ft.state)
str_ft.area_code = le.fit_transform(str_ft.area_code)
str_ft.international_plan = le.fit_transform(str_ft.international_plan)
str_ft.voice_mail_plan = le.fit_transform(str_ft.voice_mail_plan)
str_ft.churn = le.fit_transform(str_ft.churn)
str_ft

      state  area_code  international_plan  voice_mail_plan  churn
0        35          1                   0                1      0
1        31          1                   0                0      0
2        35          0                   1                0      0
3        36          1                   1                0      0
4        19          2                   0                1      0
...     ...        ...                 ...              ...    ...
4245     26          1                   0                0      0
4246     49          0                   0                0      0
4247     27          0                   0                0      0
4248     11          0                   0                1      0
4249     46          1                   0                1      0

[4250 rows x 5 columns]

In [8]:
final_X_train = pd.concat([scaled_num,str_ft], axis=1)
final_X_train

,account_length,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,state,area_code,international_plan,voice_mail_plan,churn
0,0.438017,0.500000,0.459744,0.745455,0.459672,0.544114,0.605882,0.544204,0.644051,0.588571,0.644344,0.685,0.15,0.685185,0.111111,35,1,0,1,0
1,0.561983,0.000000,0.692461,0.690909,0.692436,0.337323,0.647059,0.337263,0.411646,0.594286,0.411930,0.610,0.25,0.609259,0.000000,31,1,0,0,0
2,0.342975,0.000000,0.851778,0.430303,0.851740,0.172279,0.517647,0.172233,0.498481,0.508571,0.498593,0.330,0.35,0.329630,0.222222,35,0,1,0,0
3,0.305785,0.000000,0.474253,0.684848,0.474230,0.412747,0.717647,0.412901,0.473165,0.691429,0.473270,0.505,0.15,0.505556,0.333333,36,1,1,0,0
4,0.495868,0.461538,0.620768,0.533333,0.620649,0.969942,0.635294,0.969876,0.538228,0.674286,0.538548,0.375,0.35,0.375926,0.333333,19,2,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,0.338843,0.000000,0.535704,0.424242,0.535643,0.678542,0.517647,0.678454,0.541013,0.451429,0.541362,0.515,0.30,0.514815,0.000000,26,1,0,0,0
4246,0.297521,0.000000,0.506117,0.539394,0.506024,0.365154,0.482353,0.365095,0.471392,0.508571,0.471581,0.575,0.30,0.575926,0.333333,49,0,0,0,0
4247,0.305785,0.000000,0.485633,0.612121,0.485609,0.537434,0.741176,0.537328,0.326835,0.594286,0.326956,0.345,0.35,0.344444,0.111111,27,0,0,0,0
4248,0.202479,0.769231,0.670555,0.769697,0.670515,0.620651,0.741176,0.620825,0.753165,0.662857,0.753517,0.495,0.25,0.494444,0.222222,11,0,0,1,0
4249,0.351240,0.653846,0.368137,0.618182,0.368139,0.743390,0.611765,0.743287,0.391899,0.571429,0.392234,0.465,0.80,0.464815,0.000000,46,1,0,1,0

In [9]:
training = final_X_train.head(3400)

In [10]:
X = final_X_train[3400:].drop(['churn'], axis='columns')
Y = final_X_train[3400:].churn

In [11]:
final_X_train.describe()

,account_length,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,state,area_code,international_plan,voice_mail_plan,churn
count,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000
mean,0.410067,0.146765,0.512830,0.605499,0.512796,0.557122,0.589273,0.557139,0.507666,0.570512,0.507816,0.512804,0.221318,0.512899,0.173229,26.094118,0.992941,0.093176,0.261647,0.140706
std,0.164043,0.258459,0.153663,0.120308,0.153650,0.139854,0.117109,0.139856,0.127477,0.114818,0.127514,0.138005,0.123153,0.138001,0.145715,14.769049,0.709978,0.290714,0.439583,0.347759
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.297521,0.000000,0.407752,0.527273,0.407714,0.461801,0.511765,0.461771,0.423354,0.491429,0.423326,0.425000,0.150000,0.425926,0.111111,14.000000,0.000000,0.000000,0.000000,0.000000
50%,0.409091,0.000000,0.513371,0.606061,0.513387,0.558586,0.588235,0.558612,0.507468,0.571429,0.507597,0.515000,0.200000,0.514815,0.111111,26.000000,1.000000,0.000000,0.000000,0.000000
75%,0.520661,0.307692,0.615078,0.684848,0.614960,0.650640,0.670588,0.650540,0.594177,0.645714,0.594260,0.600000,0.300000,0.600000,0.222222,39.000000,1.000000,0.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,50.000000,2.000000,1.000000,1.000000,1.000000

In [12]:
x = training.drop(['churn'], axis='columns')

In [13]:
y = training.churn

DecisionTree

In [14]:
from sklearn import tree
tree = tree.DecisionTreeClassifier()

In [15]:
tree.fit(x,y)

DecisionTreeClassifier()

In [16]:
tree.score(x,y)

1.0

In [17]:
tree.score(X,Y)

0.9235294117647059

LogisticRegression

In [18]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(solver='lbfgs', max_iter=250)
log_reg

LogisticRegression(max_iter=250)

In [19]:
log_reg.fit(x,y)

LogisticRegression(max_iter=250)

In [20]:
log_reg.score(x,y) #vuol dire devo migliorarlo?

0.8679411764705882

In [21]:
log_reg.score(X,Y) #com'Ã¨ possibile si valuti meglio il modello sul test che sul train?

0.8694117647058823

In [22]:
from sklearn import svm

In [23]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20],
    'kernel': ['rbf','linear']
}, cv=10, return_train_score=False)
clf.fit(x, y)
clf.cv_results_

{'mean_fit_time': array([ 0.15337746, 23.71675475,  0.16871717, 60.73091416,  0.18120863,
        70.32596166]),
 'std_fit_time': array([0.01336091, 2.22567417, 0.00936915, 6.04732688, 0.00765592,
        6.73560044]),
 'mean_score_time': array([0.01000886, 0.00648134, 0.00780413, 0.00482295, 0.00780971,
        0.00987282]),
 'std_score_time': array([0.00678481, 0.00647575, 0.00780414, 0.0059363 , 0.00780971,
        0.00717453]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': array([0.86176471, 0.86176471, 0.86470588, 0.86176471, 0.86176471,
        0.86176471]),
 'split1_test_score': array([0.85882353, 0.85882353, 0.87058824, 0.85882353, 0.87352941,
        0.85882353]),
 'split2_test_score': array([0.85882353, 0.85882353, 0.85882353, 0.85882353, 0.85588235,
        0.85882353]),
 'split3_test_score': array([0.85882353, 0.85882353, 0.86470588, 0.85882353, 0.86764706,
        0.85882353]),
 'split4_test_score': array([0.85882353, 0.85882353, 0.87058824, 0.85882353, 0.86764706,
        0.85882353]),
 'split5_test_score': array([0.85882353, 0.85882353, 0.86176471, 0.85882353, 0.85882353,
        0.85882353]),
 'split6_test_score': array([0.85882353, 0.85882353, 0.85294118, 0.85882353, 0.86470588,
        0.85882353]),
 'split7_test_score': array([0.85882353, 0.85882353, 0.85882353, 0.85882353, 0.85294118,
        0.85882353]),
 'split8_test_score': array([0.85882353, 0.85882353, 0.85294118, 0.85882353, 0.85882353,
        0.85882353]),
 'split9_test_score': array([0.85882353, 0.85882353, 0.85588235, 0.85882353, 0.87058824,
        0.85882353]),
 'mean_test_score': array([0.85911765, 0.85911765, 0.86117647, 0.85911765, 0.86323529,
        0.85911765]),
 'std_test_score': array([0.00088235, 0.00088235, 0.00614136, 0.00088235, 0.00634231,
        0.00088235]),
 'rank_test_score': array([3, 3, 2, 3, 1, 3])}

In [24]:
dd = pd.DataFrame(clf.cv_results_)
dd

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,split5_test_score,split6_test_score,split7_test_score,split8_test_score,split9_test_score,mean_test_score,std_test_score,rank_test_score
0,0.153377,0.013361,0.010009,0.006785,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.861765,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.859118,0.000882,3
1,23.716755,2.225674,0.006481,0.006476,1,linear,"{'C': 1, 'kernel': 'linear'}",0.861765,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.859118,0.000882,3
2,0.168717,0.009369,0.007804,0.007804,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.864706,0.870588,0.858824,0.864706,0.870588,0.861765,0.852941,0.858824,0.852941,0.855882,0.861176,0.006141,2
3,60.730914,6.047327,0.004823,0.005936,10,linear,"{'C': 10, 'kernel': 'linear'}",0.861765,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.859118,0.000882,3
4,0.181209,0.007656,0.007810,0.007810,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.861765,0.873529,0.855882,0.867647,0.867647,0.858824,0.864706,0.852941,0.858824,0.870588,0.863235,0.006342,1
5,70.325962,6.735600,0.009873,0.007175,20,linear,"{'C': 20, 'kernel': 'linear'}",0.861765,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.858824,0.859118,0.000882,3

In [25]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf','linear']  
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=2
)
rs.fit(x,y)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0       1       linear         0.859118
1      10       linear         0.859118